### ISSUE TITLE
hidden field "cf-turnstile-response" submitted two times

### ISSUE THREAD

**Issue by logemann** [cometkim/gatsby-plugin-turnstile#22]
Just implemented your turnstile plugin by just doing:

```
import { TurnstileImplicitFormInput } from 'gatsby-plugin-turnstile/src';
...
<TurnstileImplicitFormInput/>
```

in the frontend. When submitting my form, my backend gets two times the cf-turnstile-response parameter which of course doesnt pass the check by cloudflare when doing the backend check. 

Any idea what this is?

**Comment by cometkim** [comment]
Well, I have been using it since the first version without any problems. Maybe it's an environment issue. Can you share If your site is open source? or any reproduction?

**Comment by logemann** [comment]
Project was dismissed. You can close this one.

**Comment by cometkim** [comment]
yep, please let me know If you discover anything later :)
